73 Emotion Learning/GUI/Emotional_Learning/Emotional_Learning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('register.urls')),
]

73 Emotion Learning/GUI/Emotional_Learning/register/urls.py
from django.urls import path
from . import views

app_name = "register"

urlpatterns = [
    path("", views.home, name="home"),
    path('signin', views.signin, name="signin"),
    path('signup', views.signup, name="signup"),
    path('signout', views.signout, name="signout"),
    path('camera_stream', views.camera_stream, name="camera_stream"),
    path('end_camera_stream', views.stop_camera_stream, name="end_camera_stream"),
    path('history', views.history, name="history"),
    path('session_history/<str:id>', views.session_history, name="session_history")
]

73 Emotion Learning/GUI/Emotional_Learning/register/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class EmotionHistory(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_id')
    session_id = models.CharField(max_length=30, null=False, blank=False)
    dated_at = models.DateField(auto_now_add=True)
    time_added = models.TimeField(auto_now_add=True)
    label = models.CharField(max_length=15)

73 Emotion Learning/GUI/Emotional_Learning/register/views.py
import re
from datetime import datetime

import cv2
import time
from django.db.models import Q
from django.http import StreamingHttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from utils.function import text_drawing, generate_session_id, predictor
from .models import EmotionHistory
from itertools import groupby


camera = None  # Declare the camera object at the module level


# Create your views here.
# home view
def home(request):
    if request.user.is_authenticated:
        return render(request, 'home_old.html')

    return render(request, 'register/SignIn.html')


def camera_stream(request):
    return StreamingHttpResponse(stream_camera(request), content_type="multipart/x-mixed-replace;boundary=frame")


def stream_camera(request):
    global camera
    detection_time_period = 10
    last_call_time = time.time()
    session_id = generate_session_id(request)
    camera = cv2.VideoCapture(0)  # Use the default camera (change the index if needed)
    label = None
    while True:

        success, frame = camera.read()
        if not success:
            break

        current_time = time.time()
        if current_time - last_call_time >= detection_time_period:
            label = predictor(frame)
            last_call_time = current_time
            last_call_time_formatted = datetime.now().time()

            EmotionHistory.objects.create(user_id=request.user, label=label, session_id=session_id)

        if label is not None:
            frame = text_drawing(frame, label, last_call_time_formatted)

        _, buffer = cv2.imencode('.jpg', frame)
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + buffer.tobytes() + b'\r\n')

    camera.release()


# stop camera stream
def stop_camera_stream(request):
    global camera
    if camera is not None:
        camera.release()  # Release the camera object
        camera = None  # Set the camera object to None
    return redirect('register:history')


def history(request):
    global camera
    if camera is not None:
        camera.release()  # Release the camera object
        camera = None  # Set the camera object to None

    records = EmotionHistory.objects.filter(user_id=request.user).order_by('session_id')

    # Group records by session ID
    grouped_records = {}
    for key, group in groupby(records, key=lambda x: x.session_id):
        grouped_records[key] = list(group)

    context = {'grouped_records': grouped_records}
    return render(request, "history.html", context)


def session_history(request, id):
    records = EmotionHistory.objects.filter(session_id=id)
    context = {'records': records}
    return render(request, "session_history.html", context)


# signup view
def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['pass']
        retype_password = request.POST['re_pass']

        # validate user data
        if User.objects.filter(username=username):
            messages.error(request, "Username already exists!")
            return redirect('register:signup')

        if len(username) > 15:
            messages.error(request, "Username must be under 15 characters")
            return redirect('register:signup')

        if not username.isalnum():
            messages.error(request, "Username must be Alpha-Numeric")
            return redirect('register:signup')

        if User.objects.filter(email=email):
            messages.error(request, "Email already registered!")
            return redirect('register:signup')

        if password != retype_password:
            messages.error(request, "Passwords didn't matched")
            return redirect('register:signup')

        password_pattern = "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$"
        if re.match(password_pattern, password) is None:
            messages.error(request, "Password requirements failed")
            return redirect('register:signup')

        my_user = User.objects.create_user(username=username, email=email, password=password)
        my_user.save()

        messages.success(request,
                         "Your Account has been created Successfully.")

        return redirect('register:signin')
    return render(request, 'register/SignUp.html')


# login view
def signin(request):
    if request.method == "POST":
        name = request.POST['name']
        password = request.POST['pass']

        user = authenticate(username=name, password=password)

        if user is not None:
            login(request, user)
            return redirect('register:home')
        else:
            messages.error(request, "Bad Credentials")
            return redirect('register:signin')
    return render(request, 'register/SignIn.html')


# logout view
def signout(request):
    logout(request)
    return redirect('register:home')

73 Emotion Learning/GUI/Emotional_Learning/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Emotion Learning</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'images/emotion-scientists.jpg' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main_student.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <!--===============================================================================================-->
    <!-- Include Toastr CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet"/>
    <!--===============================================================================================-->
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    {% block style %}
    {% endblock %}
</head>


<body>
    <div class="">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark pl-5 pr-5">
            <a class="navbar-brand" href="{% url 'register:home' %}">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'register:home' %}">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register:history' %}">History</a>
                    </li>
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'payapp:request' %}">Request</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'payapp:transactions' %}">Transactions</a>#}
{#                    </li>#}

{#                    {% if request.user.is_superuser %}#}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" href="{% url 'payapp:view_users' %}">Users</a>#}
{#                        </li>#}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" href="{% url 'register:register_admin' %}">Register Admin</a>#}
{#                        </li>#}
{#                    {% endif %}#}

                </ul>

                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-user-circle" aria-hidden="true"></i> {{ request.user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'register:signout' %}">Profile</a>
                                <a class="dropdown-item" href="#">Settings</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'register:signout' %}">Logout</a>
                            </div>
                        </li>
                    </ul>

                {% else %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register:signin' %}">Login</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>
    </div>

    {% block content %}
    {% endblock %}


    <!--===============================================================================================-->
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <!--===============================================================================================-->
    <!-- Include Toastr JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <!--===============================================================================================-->



    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>

    {% block script %}
    {% endblock %}
</body>
</html>

73 Emotion Learning/GUI/Emotional_Learning/templates/history.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="container-fluid">
        <div class="row" style="padding-top: 100px">
            <img src="{% static 'images/main_logo.png' %}" alt="" style="display: block; margin: 0 auto">
        </div>
    </div>

    <div class="heading-wrapper" style="text-align: center">
        <h2 style="font-family: Montserrat-Bold; color: #333333">Emotion Learning</h2>
        <div class="divider"></div>
    </div>

    <div class="contact1">
        <div class="container-contact1">
            <h1 class="" style="font-family: Montserrat-Bold; margin: 0 auto 25px auto; text-align: center">Detection
                History</h1>

            <div class="table-wrapper" style="width: 100%; overflow-y: scroll; height: 450px">
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Session ID</th>
                        <th scope="col">Username</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if request.user.is_authenticated %}
                        {% for session_id, records in grouped_records.items %}
                                <tr>
                                    <th><a href="{% url 'register:session_history' id=session_id %}">{{ session_id }}</a></th>
                                    <th>{{ request.user.username }}</th>
                                </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>

    <footer class="bg-dark text-center text-lg-start" style="margin-top: 20px; color: #ffffff">
        <div class="text-center p-3">
            &copy; 2023 Pay APP. All rights reserved.
        </div>
    </footer>

{% endblock %}

73 Emotion Learning/GUI/Emotional_Learning/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="jumbotron text-center">
        <h2 style="font-family: Montserrat-Bold; color: #333333">Welcome to Emotion Learning APP</h2>
        <p style="font-family: Montserrat-Bold; margin-bottom: 20px">Detect the Emotion on Real Time.</p>
        <i class="fa fa-user-circle" aria-hidden="true"></i>
{#        <a class="btn button-main" href="{% url 'student:index' %}" role="button">Get Started</a>#}
    </div>

    <div class="heading-wrapper" style="text-align: center">
        <h2 style="font-family: Montserrat-Bold; color: #333333">Emotion Learning</h2>
        <div class="divider"></div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'images/icons/person.png' %}" id="camera-stream">
            </div>
            <div class="col-md-6">
                <div class="button-wrapper" style="position: absolute; left: 30%; top: 32%; margin: 0">
                    <button id="start" class="btn btn-primary" style="display: block; border-radius: 10px; height: 50px; width: 150px">Start Session</button>
                    <button id="end" class="btn btn-danger" style="display: block; border-radius: 10px; height: 50px; width: 150px; margin-top: 10px" disabled>End Session</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row" style="padding-top: 100px">
            <img src="{% static 'images/main_logo.png' %}" alt="" style="display: block; margin: 0 auto">
        </div>
    </div>

    <footer class="bg-dark text-center text-lg-start" style="margin-top: 20px; color: #ffffff">
        <div class="text-center p-3">
            &copy; 2023 Pay APP. All rights reserved.
        </div>
    </footer>

{% endblock %}


{% block script %}
    <script>
        $("#start").on('click', function (){
            $("#start").prop('disabled', true);
            $("#end").prop('disabled', false);
            var imgElement = document.getElementById('camera-stream');
            imgElement.src = "{% url 'register:camera_stream' %}";
        });

        $("#end").on('click', function () {
            $("#start").prop('disabled', false);
            $("#end").prop('disabled', true);
            var imgElement = document.getElementById('camera-stream');
            imgElement.src = "{% url 'register:end_camera_stream' %}";
            imgElement.src = "{% static 'images/icons/person.png' %}";
        });
    </script>
{% endblock %}

73 Emotion Learning/GUI/Emotional_Learning/templates/home_old.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="jumbotron text-center">
        <h2 style="font-family: Montserrat-Bold; color: #333333">Welcome to Emotion Learning APP</h2>
        <p style="font-family: Montserrat-Bold; margin-bottom: 20px">Detect the Emotion on Real Time.</p>
        <i class="fa fa-user-circle" aria-hidden="true"></i>
{#        <a class="btn button-main" href="{% url 'student:index' %}" role="button">Get Started</a>#}
    </div>

    <div class="heading-wrapper" style="text-align: center">
        <h2 style="font-family: Montserrat-Bold; color: #333333">Emotion Learning</h2>
        <div class="divider"></div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'images/icons/person.png' %}" id="camera-stream">
            </div>
            <div class="col-md-6">
                <div class="button-wrapper" style="position: absolute; left: 30%; top: 32%; margin: 0">
                    <button id="start" class="btn btn-primary" style="display: block; border-radius: 10px; height: 50px; width: 150px">Start Session</button>
                    <button id="end" class="btn btn-danger" style="display: block; border-radius: 10px; height: 50px; width: 150px; margin-top: 10px" disabled>End Session</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row" style="padding-top: 100px">
            <img src="{% static 'images/main_logo.png' %}" alt="" style="display: block; margin: 0 auto">
        </div>
    </div>

    <footer class="bg-dark text-center text-lg-start" style="margin-top: 20px; color: #ffffff">
        <div class="text-center p-3">
            &copy; 2023 Pay APP. All rights reserved.
        </div>
    </footer>

{% endblock %}


{% block script %}
    <script>
        $("#start").on('click', function (){
            $("#start").prop('disabled', true);
            $("#end").prop('disabled', false);
            var imgElement = document.getElementById('camera-stream');
            imgElement.src = "{% url 'register:camera_stream' %}";
        });

        $("#end").on('click', function () {
            $("#start").prop('disabled', false);
            $("#end").prop('disabled', true);
            var imgElement = document.getElementById('camera-stream');
            imgElement.src = "{% url 'register:end_camera_stream' %}";
            imgElement.src = "{% static 'images/icons/person.png' %}";
        });
    </script>
{% endblock %}

73 Emotion Learning/GUI/Emotional_Learning/templates/register/Forgot_Password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="main">

    <!-- Sign up form -->
    <section class="signup">
        <div class="container">
            <div class="signup-content">
                <div class="signup-form">
                    <h2 class="form-title">Recover Password</h2>

                    <form action="{% url 'forgot_password' %}" method="POST" class="register-form" id="register-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="email"><i class="zmdi zmdi-email"></i></label>
                            <input type="email" name="email" id="email" placeholder="Enter recovery email"/>
                        </div>
                        <div class="form-group form-button">
                            <input type="submit" name="signup" id="signup" class="form-submit" value="Send"/>
                        </div>
                    </form>

                    {% for message in messages %}
                        <div style="margin-bottom: 20px">
                            <span style="color: #e72734">{{ message }}</span>
                        </div>
                    {% endfor %}
                </div>
                <div class="signup-image">
                    <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'signin' %}" class="signup-image-link">SignIn</a>
                </div>
            </div>
        </div>
    </section>


</div>

<!-- JS -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

73 Emotion Learning/GUI/Emotional_Learning/templates/register/Reset_Password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="main">

    <!-- Sign up form -->
    <section class="signup">
        <div class="container">
            <div class="signup-content">
                <div class="signup-form">
                    <h2 class="form-title">Sign up</h2>

                    {% for message in messages %}
                        <div style="margin-bottom: 20px">
                            <span style="color: #e72734">{{ message }}</span>
                        </div>
                    {% endfor %}

                    <form action="{% url 'update_password' %}" method="POST" class="register-form" id="register-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                            <input type="password" name="pass" id="pass" placeholder="Password"/>
                        </div>
                        <div class="form-group">
                            <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                            <input type="password" name="re_pass" id="re_pass" placeholder="Repeat your password"/>
                        </div>
                        <div class="form-group">
                            <ul style="color: #777777; padding-left: 17px">
                                <li>atleast 8 characters</li>
                                <li>alteast 1 capital or small latter</li>
                                <li>atleast contain 1 special character</li>
                            </ul>
                        </div>
                        <input type="hidden" name="uidb64" value="{{ uidb64 }}">
                        <input type="hidden" name="token" value="{{ token }}">
                        <div class="form-group form-button">
                            <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                        </div>
                    </form>
                </div>
                <div class="signup-image">
                    <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'signin' %}" class="signup-image-link">I am already member</a>
                </div>
            </div>
        </div>
    </section>


</div>

<!-- JS -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

73 Emotion Learning/GUI/Emotional_Learning/templates/register/SignIn.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container-fluid">
        <div class="row" style="text-align: center; padding-top: 100px"><img src="{% static 'images/main_logo.png' %}" alt=""></div>
    </div>

    {# main login form div #}
    <div class="main">

        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="{% static 'images/signin-image.jpg' %}" alt="sing up image"></figure>
                        <a href="{% url 'register:signup' %}" class="signup-image-link">Create an account</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Sign In</h2>

                        {% for message in messages %}
                            <div style="margin-bottom: 20px">
                                <span style="color: #e72734">{{ message }}</span>
                            </div>
                        {% endfor %}

                        <form method="POST" action="{% url 'register:signin' %}" class="register-form" id="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="name" id="your_name" placeholder="Username"/>
                            </div>
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="pass" id="your_pass" placeholder="Password"/>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                                <a href="{% url 'register:signin' %}" style="text-decoration: none; margin-left: 5px">Forgot Password?</a>
                            </div>
                        </form>
                        <div class="social-login">
                            <span class="social-label">Or login with</span>
                            <ul class="socials">
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>