59 PayAPP Django/PayApp/code/webapps2023/payapp/urls.py


from django.urls import path, include
from . import views

app_name = "payapp"

urlpatterns = [
    path('transfer', views.transfer, name="transfer"),
    path('request', views.send_request, name="request"),
    path('transactions', views.view_transactions, name="transactions"),
    path('view_users', views.view_users, name="view_users"),
    path('notification', views.notification, name="notification"),
    # path('request_decision', views.request_decision, name="request_decision"),
    path('request_decision/<int:id>/', views.request_decision, name="request_decision_id"),
    path('request_action/<int:id>/<str:decision>/', views.request_action, name="request_action")
]

59 PayAPP Django/PayApp/code/webapps2023/register/urls.py
from django.urls import path, include
from . import views

app_name = "register"

urlpatterns = [
    path("", views.home, name="home"),
    path('signin', views.signin, name="signin"),
    path('signup', views.signup, name="signup"),
    path('signout', views.signout, name="signout"),
    path('register_admin', views.add_admin, name='register_admin'),
    path('profile', views.view_profile, name="profile")
]

59 PayAPP Django/PayApp/code/webapps2023/webapps2023/urls.py
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from django.urls import re_path as url
# from django.conf.urls import url

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('register.urls')),
    path("pay", include('payapp.urls')),

    # url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

59 PayAPP Django/PayApp/code/webapps2023/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Attendance System</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'images/coin.png' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main_student.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <!--===============================================================================================-->
    <!-- Include Toastr CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet"/>
    <!--===============================================================================================-->
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    {% block style %}
    {% endblock %}
</head>


<body>
    <div class="">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark pl-5 pr-5">
            <a class="navbar-brand" href="{% url 'register:home' %}">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'register:home' %}">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'payapp:transfer' %}">Transfer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'payapp:request' %}">Request</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'payapp:transactions' %}">Transactions</a>
                    </li>

                    {% if request.user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'payapp:view_users' %}">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register:register_admin' %}">Register Admin</a>
                        </li>
                    {% endif %}

                </ul>

                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        <a class="nav-link" href="{% url 'payapp:notification' %}" id="" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-bell" aria-hidden="true"></i>
                            <span class="notification-count">{{ count }}</span> <!-- Number of notifications -->
                        </a>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-user-circle" aria-hidden="true"></i> {{ request.user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'register:profile' %}">Profile</a>
                                <a class="dropdown-item" href="#">Settings</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'register:signout' %}">Logout</a>
                            </div>
                        </li>
                        <li class="nav-item float-right ml-auto">
                            <a class="nav-link" href="#"
                               style="font-size: 14px">{{ user.currency }}: {{ user.balance }}</a>
                        </li>
                    </ul>

                {% else %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register:signin' %}">Login</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>
    </div>

    {% block content %}
    {% endblock %}


    <!--===============================================================================================-->
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <!--===============================================================================================-->
    <!-- Include Toastr JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <!--===============================================================================================-->



    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>

    {% block script %}
    {% endblock %}
</body>
</html>

59 PayAPP Django/PayApp/code/webapps2023/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="jumbotron text-center">
        <h2 style="font-family: Montserrat-Bold; color: #333333">Welcome to Pay APP System</h2>
        <p style="font-family: Montserrat-Bold; margin-bottom: 20px">Send and Received Payments with ease.</p>
        <i class="fa fa-user-circle" aria-hidden="true"></i>
{#        <a class="btn button-main" href="{% url 'student:index' %}" role="button">Get Started</a>#}
    </div>

    <div class="container">
        <div class="heading-wrapper" style="text-align: center">
            <h2 style="font-family: Montserrat-Bold; color: #333333">Features</h2>
            <div class="divider"></div>
        </div>
        <div class="row gx-5">
            <div class="col feature-col">
                <h3>Send Payment</h3>
                <p>Send payment to any register user with ease</p>
                <a class="btn btn-secondary" href="{% url 'payapp:transfer' %}" role="button">Transfer Payment</a>
            </div>
            <div class="col feature-col">
                <h3>Receive Payments</h3>
                <p>Request payment for any valid user instantly.</p>
                <a class="btn btn-secondary" href="{% url 'payapp:request' %}" role="button">Request Payment</a>
            </div>
        </div>
    </div>

    <footer class="bg-dark text-center text-lg-start" style="margin-top: 20px; color: #ffffff">
        <div class="text-center p-3">
            &copy; 2023 Pay APP. All rights reserved.
        </div>
    </footer>

{% endblock %}