47 LoveJoy Djnago Site/Lovejoy/Lovejoy/urls.py
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('authentication.urls')),
    path('evaluation', include('RequestEvaluation.urls')),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

47 LoveJoy Djnago Site/Lovejoy/RequestEvaluation/urls.py
from django.urls import path, include
from . import views

app_name = "request_evaluation"

urlpatterns = [
    path('create_request', views.create_request, name="create_request"),
]

47 LoveJoy Djnago Site/Lovejoy/authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('signin', views.signin, name="signin"),
    path('signup', views.signup, name="signup"),
    path('signout', views.signout, name="signout"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('forgot_password', views.forgot_password, name="forgot_password"),
    path('reset_password/<uidb64>/<token>', views.reset_password, name="reset_password"),
    path('update_password', views.update_password, name="update_password")
]

47 LoveJoy Djnago Site/Lovejoy/authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class PhoneNumber(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    phone = PhoneNumberField(null=False, blank=False, unique=True)

47 LoveJoy Djnago Site/Lovejoy/authentication/views.py
import re

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
import phonenumbers
from .models import PhoneNumber

from RequestEvaluation.models import EvaluateRequest
from .tokens import generate_token

from Lovejoy import settings


# Create your views here.
def home(request):
    if request.user.is_superuser:
        evaluation_requests = EvaluateRequest.objects.all()
        dict_obj = {'evaluation_requests': evaluation_requests}
        return render(request, 'authentication/index.html', dict_obj)
    return render(request, 'authentication/index.html')


def signup(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        password = request.POST['pass']
        retype_password = request.POST['re_pass']

        if User.objects.filter(username=name):
            messages.error(request, "Username already exists!")
            return redirect('signup')

        if len(name) > 10:
            messages.error(request, "Username must be under 10 characters")
            return redirect('signup')

        if not name.isalnum():
            messages.error(request, "Username must be Alpha-Numeric")
            return redirect('signup')

        if User.objects.filter(email=email):
            messages.error(request, "Email already registered!")
            return redirect('signup')

        parse_phone = phonenumbers.parse(phone, "UK")
        if not phonenumbers.is_possible_number(parse_phone):
            messages.error(request, "Phone should be in format!")
            return redirect('signup')

        if password != retype_password:
            messages.error(request, "Passwords didn't matched")
            return redirect('signup')

        password_pattern = "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$"
        if re.match(password_pattern, password) is None:
            messages.error(request, "Password requirements failed")
            return redirect('signup')

        my_user = User.objects.create_user(username=name, email=email, password=password)
        my_user.is_active = False
        my_user.save()

        user = User.objects.get(username=name)
        PhoneNumber.objects.create(user=user, phone=phone)

        # welcome email
        subject = "Welcome to LoveJoy"
        message = "Hello " + my_user.username + "!! \n Welcome to LoveJoy!! \n Thank you for visiting our website \n " \
                                                "We have also sent you a confirmation email, please confirm your " \
                                                "email to activate your account. \n\n Team LoveJoy "

        from_email = settings.EMAIL_HOST_USER
        to_list = [my_user.email]
        send_mail(subject, message, from_email, to_list, fail_silently=True)

        # confirmation email
        current_site = get_current_site(request)
        email_subject = "Confirm your email @ LoveJoy"
        message2 = render_to_string('email_confirmation.html', {
            'name': my_user.username,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(my_user.pk)),
            'token': generate_token.make_token(my_user)
        })
        email = EmailMessage(
            email_subject,
            message2,
            settings.EMAIL_HOST_USER,
            [my_user.email]
        )
        email.fail_silently = True
        email.send()

        messages.success(request,
                         "Your Account has been created Successfully. We have sent you a confirmation email. Use "
                         "activation link to activate your account.")

        return redirect('signup')
    return render(request, 'authentication/SignUp.html')


def signin(request):
    if request.method == "POST":
        name = request.POST['name']
        password = request.POST['pass']

        user = authenticate(username=name, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Bad Credentials")
            return redirect('signin')
    return render(request, 'authentication/SignIn.html')


def signout(request):
    logout(request)
    return redirect('home')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        myuser = None

    if myuser is not None and generate_token.check_token(myuser, token):
        myuser.is_active = True
        myuser.save()
        login(request, myuser)
        return render(request, 'authentication/index.html')
    else:
        return render(request, 'activation_failed.html')


def forgot_password(request):
    if request.method == "POST":
        email = request.POST['email']
        my_user = User.objects.get(email=email)
        if my_user is not None:

            # confirmation email
            current_site = get_current_site(request)
            email_subject = "Reset your Password @ LoveJoy"
            message2 = render_to_string('Reset_Password_Link.html', {
                'name': my_user.username,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(my_user.pk)),
                'token': generate_token.make_token(my_user)
            })
            email = EmailMessage(
                email_subject,
                message2,
                settings.EMAIL_HOST_USER,
                [my_user.email]
            )
            email.fail_silently = True
            email.send()

            messages.success(request,
                             "Password reset link have been sent to your email address. Use the link to reset your "
                             "password.")
            return redirect('signin')
        else:
            messages.error(request, "Your email didn't belong to any account. Kindly submit a valid email address or "
                                    "SigUp for the new account.")

    return render(request, 'authentication/Forgot_Password.html')


def reset_password(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        myuser = None

    if myuser is not None and generate_token.check_token(myuser, token):
        return render(request, 'authentication/Reset_Password.html', {'uidb64': uidb64, 'token': token})
    else:
        messages.success(request, 'Your link is not working, please try again later.')
        return redirect('signin')


def update_password(request):
    if request.method == "POST":
        uidb64 = request.POST['uidb64']
        token = request.POST['token']

        password = request.POST['pass']
        retype_password = request.POST['re_pass']

        if password != retype_password:
            messages.error(request, "Passwords didn't matched")
            return redirect('reset_password', uidb64=uidb64, token=token)

        password_pattern = "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$"
        if re.match(password_pattern, password) is None:
            messages.error(request, "Password validation failed")
            return redirect('reset_password', uidb64=uidb64, token=token)

        # extract user base on uid
        uid = force_text(urlsafe_base64_decode(uidb64))
        my_user = User.objects.get(pk=uid)
        my_user.set_password(password)
        my_user.save()

        # welcome email
        subject = "Password Reset Complete"
        message = "Hello " + my_user.username + "!! \n Your password has been set. \n You may go head and login now. " \
                                                "\n\n The LoveJoy Team "
        from_email = settings.EMAIL_HOST_USER
        to_list = [my_user.email]
        send_mail(subject, message, from_email, to_list, fail_silently=True)

        messages.success(request,
                         "Your Password has been change successfully.")

    return redirect('signin')

47 LoveJoy Djnago Site/Lovejoy/templates/authentication/Forgot_Password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="main">

    <!-- Sign up form -->
    <section class="signup">
        <div class="container">
            <div class="signup-content">
                <div class="signup-form">
                    <h2 class="form-title">Recover Password</h2>

                    <form action="{% url 'forgot_password' %}" method="POST" class="register-form" id="register-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="email"><i class="zmdi zmdi-email"></i></label>
                            <input type="email" name="email" id="email" placeholder="Enter recovery email"/>
                        </div>
                        <div class="form-group form-button">
                            <input type="submit" name="signup" id="signup" class="form-submit" value="Send"/>
                        </div>
                    </form>

                    {% for message in messages %}
                        <div style="margin-bottom: 20px">
                            <span style="color: #e72734">{{ message }}</span>
                        </div>
                    {% endfor %}
                </div>
                <div class="signup-image">
                    <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'signin' %}" class="signup-image-link">SignIn</a>
                </div>
            </div>
        </div>
    </section>


</div>

<!-- JS -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

47 LoveJoy Djnago Site/Lovejoy/templates/authentication/Reset_Password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="main">

    <!-- Sign up form -->
    <section class="signup">
        <div class="container">
            <div class="signup-content">
                <div class="signup-form">
                    <h2 class="form-title">Sign up</h2>

                    {% for message in messages %}
                        <div style="margin-bottom: 20px">
                            <span style="color: #e72734">{{ message }}</span>
                        </div>
                    {% endfor %}

                    <form action="{% url 'update_password' %}" method="POST" class="register-form" id="register-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                            <input type="password" name="pass" id="pass" placeholder="Password"/>
                        </div>
                        <div class="form-group">
                            <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                            <input type="password" name="re_pass" id="re_pass" placeholder="Repeat your password"/>
                        </div>
                        <div class="form-group">
                            <ul style="color: #777777; padding-left: 17px">
                                <li>atleast 8 characters</li>
                                <li>alteast 1 capital or small latter</li>
                                <li>atleast contain 1 special character</li>
                            </ul>
                        </div>
                        <input type="hidden" name="uidb64" value="{{ uidb64 }}">
                        <input type="hidden" name="token" value="{{ token }}">
                        <div class="form-group form-button">
                            <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                        </div>
                    </form>
                </div>
                <div class="signup-image">
                    <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'signin' %}" class="signup-image-link">I am already member</a>
                </div>
            </div>
        </div>
    </section>


</div>

<!-- JS -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

47 LoveJoy Djnago Site/Lovejoy/templates/authentication/SignIn.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <div class="main">

        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="{% static 'images/signin-image.jpg' %}" alt="sing up image"></figure>
                        <a href="{% url 'signup' %}" class="signup-image-link">Create an account</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Sign In</h2>

                        {% for message in messages %}
                            <div style="margin-bottom: 20px">
                                <span style="color: #e72734">{{ message }}</span>
                            </div>
                        {% endfor %}

                        <form method="POST" action="{% url 'signin' %}" class="register-form" id="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="name" id="your_name" placeholder="Your Name"/>
                            </div>
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="pass" id="your_pass" placeholder="Password"/>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                                <a href="{% url 'forgot_password' %}" style="text-decoration: none; margin-left: 5px">Forgot Password?</a>
                            </div>
                        </form>
                        <div class="social-login">
                            <span class="social-label">Or login with</span>
                            <ul class="socials">
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

47 LoveJoy Djnago Site/Lovejoy/templates/authentication/SignUp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="main">

    <!-- Sign up form -->
    <section class="signup">
        <div class="container">
            <div class="signup-content">
                <div class="signup-form">
                    <h2 class="form-title">Sign up</h2>

                    {% for message in messages %}
                        <div style="margin-bottom: 20px">
                            <span style="color: #e72734">{{ message }}</span>
                        </div>
                    {% endfor %}

                    <form action="{% url 'signup' %}" method="POST" class="register-form" id="register-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            <input type="text" name="name" id="name" placeholder="Your Name"/>
                        </div>
                        <div class="form-group">
                            <label for="email"><i class="zmdi zmdi-email"></i></label>
                            <input type="email" name="email" id="email" placeholder="Your Email"/>
                        </div>
                        <div class="form-group">
                            <label for="phone"><i class="zmdi zmdi-phone"></i></label>
                            <input type="text" name="phone" id="email" placeholder="+44XXXXXXX max(15)"/>
                        </div>
                        <div class="form-group">
                            <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                            <input type="password" name="pass" id="pass" placeholder="Password"/>
                        </div>
                        <div class="form-group">
                            <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                            <input type="password" name="re_pass" id="re_pass" placeholder="Repeat your password"/>
                        </div>
                        <div class="form-group">
                            <ul style="color: #777777; padding-left: 17px">
                                <li>atleast 8 characters</li>
                                <li>alteast 1 capital or small latter</li>
                                <li>atleast contain 1 special character</li>
                            </ul>
                        </div>
                        <div class="form-group form-button">
                            <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                        </div>
                    </form>
                </div>
                <div class="signup-image">
                    <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'signin' %}" class="signup-image-link">I am already member</a>
                </div>
            </div>
        </div>
    </section>


</div>

<!-- JS -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

47 LoveJoy Djnago Site/Lovejoy/templates/authentication/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>LoveJoy</title>

    <!-- load bootstrap 5 -->
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a href="{% url 'home' %}" class="navbar-brand" style="margin-left: 30px; font-size: 30px"><b style="color: #33cabb">Love</b>joy</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mynavbar">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'request_evaluation:create_request' %}">Request</a>
                    </li>
                    {% endif %}
                </ul>
                <div class="d-flex">
                    {% if user.is_authenticated %}
                        <a href="{% url 'signout' %}" type="button" style="margin-right: 20px">logout</a>
                        <span type="button">Hi {{ user }}</span>
                    {% else %}
                        <button class="btn btn-default" type="button" style="margin-right: 20px"><a href="{% url 'signup' %}">SignUp</a></button>
                        <button class="btn btn-default" type="button"><a href="{% url 'signin' %}">SignIn</a></button>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    {% if user.is_superuser %}
        <div class="container">
            <div class="row mt-5">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <h2 class="mb-5 mt-3" style="text-align: center; color: #33cabb">User Evaluation Requests</h2>
                    <table class="table" style="vertical-align: middle">
                        <thead>
                        <tr>
                            <th scope="col">User Name</th>
                            <th scope="col">Contact</th>
                            <th scope="col">Query Text</th>
                            <th scope="col">Image</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for evaluation_request in evaluation_requests %}
                            <tr>
                                <th scope="row">{{ evaluation_request.author.username }}</th>
                                <td>{{ evaluation_request.contact_via }}</td>
                                <td>{{ evaluation_request.text }}</td>
                                <td><img src="{{ evaluation_request.image.url }}" style="height: 8%; width: 8%; border-radius: 50%"></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
    {% endif %}


</body>
</html>