59 PayAPP Django/PayApp/code/webapps2023/payapp/urls.py


from django.urls import path, include
from . import views

app_name = "payapp"

urlpatterns = [
    path('transfer', views.transfer, name="transfer"),
    path('request', views.send_request, name="request"),
    path('transactions', views.view_transactions, name="transactions"),
    path('view_users', views.view_users, name="view_users"),
    path('notification', views.notification, name="notification"),
    # path('request_decision', views.request_decision, name="request_decision"),
    path('request_decision/<int:id>/', views.request_decision, name="request_decision_id"),
    path('request_action/<int:id>/<str:decision>/', views.request_action, name="request_action")
]

59 PayAPP Django/PayApp/code/webapps2023/webapps2023/urls.py
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from django.urls import re_path as url
# from django.conf.urls import url

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('register.urls')),
    path("pay", include('payapp.urls')),

    # url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

59 PayAPP Django/PayApp/code/webapps2023/payapp/models.py
from django.contrib.auth.models import User
from django.db import models
from register.models import UserExtension


# Create your models here.
class TransactionHistory(models.Model):
    transfer = "trans"
    request = "req"
    completed = 'complete'
    pending = 'pending'
    rejected = 'rejected'

    mode_choices = [
        (transfer, 'Transfer'),
        (request, 'Request'),
    ]

    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    amount = models.FloatField(blank=False, null=False)
    currency = models.CharField(max_length=3, null=False, blank=False, choices=UserExtension.currency_choices)
    mode = models.CharField(max_length=10, choices=mode_choices)
    dated_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, default='completed')

59 PayAPP Django/PayApp/code/webapps2023/payapp/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Q
from register.models import UserExtension
from .models import TransactionHistory
from register.currency_conversion import get_exchange_rate


def __get_bool(my_str):
    if my_str.lower() == 'false':
        return False
    else:
        return True


def __verify_user(request, type, validate_recipient):
    try:
        username = request.POST.get('username')
        user = User.objects.get(username=username)
        if user.id != request.user.id:
            validate_recipient = True
        else:
            label = "Transfer" if type == TransactionHistory.transfer else "Request"
            messages.error(request, f"{label} of payment to own account is not allowed!")
    except User.DoesNotExist:
        messages.error(request, "User Not Exists!")
    finally:
        return validate_recipient, username


def __make_transaction(request, type, validate_recipient):
    username = request.POST.get('username')
    amount = float(request.POST['amount'])
    base_amount = amount

    from_to = User.objects.get(id=request.user.id)
    from_to_account_details = UserExtension.objects.get(user=from_to)
    recipient_user = User.objects.get(username=username)
    recipient_account_details = UserExtension.objects.get(user=recipient_user)

    if from_to_account_details.balance >= amount or type == TransactionHistory.request:
        # save transaction
        mode = TransactionHistory.transfer if type == TransactionHistory.transfer else TransactionHistory.request
        status = TransactionHistory.completed if type == TransactionHistory.transfer else TransactionHistory.pending
        TransactionHistory.objects.create(sender=from_to, receiver=recipient_user, amount=amount, mode=mode,
                                          currency=from_to_account_details.currency, status=status)

        if type == TransactionHistory.transfer:
            # deduct balance from sender account
            from_to_account_details.balance -= amount
            from_to_account_details.save()

            # add balance in receiver account
            if from_to_account_details.currency != recipient_account_details.currency:
                rate, amount = get_exchange_rate(from_to_account_details.currency,
                                                 recipient_account_details.currency, amount)

            recipient_account_details.balance += amount
            recipient_account_details.save()

        label = "sent to" if type == TransactionHistory.transfer else "requested from"
        messages.success(request, f"An Amount of {base_amount} has been {label} {username}")
        return True, username
    else:
        messages.error(request, "you have not sufficient amount for this transaction")
        return False, username


# Create your views here.
def transfer(request):
    if request.user.is_authenticated:
        user_data = UserExtension.objects.get(user=request.user)
        notifications_count = TransactionHistory.objects.filter(
            Q(mode=TransactionHistory.request) & Q(receiver=request.user) & Q(
                status=TransactionHistory.pending)).count()

        if request.method == "POST":
            validate_recipient = __get_bool(request.POST['validate_recipient'])
            if validate_recipient:
                sufficient_balance, username = __make_transaction(request, TransactionHistory.transfer, validate_recipient)
                if sufficient_balance:
                    return render(request, 'payapp/transfer.html',
                                  {'user': user_data, 'count': notifications_count, 'recipient_user': username,
                                   'validate_recipient': validate_recipient})
            else:
                validate_recipient, username = __verify_user(request, TransactionHistory.transfer, validate_recipient)
                return render(request, 'payapp/transfer.html',
                              {'user': user_data, 'count': notifications_count, 'recipient_user': username,
                               'validate_recipient': validate_recipient})

        validate_recipient = False
        return render(request, 'payapp/transfer.html',
                      {'user': user_data, 'count': notifications_count, 'validate_recipient': validate_recipient})
    return render(request, 'register/SignIn.html')


def send_request(request):
    if request.user.is_authenticated:
        user_data = UserExtension.objects.get(user=request.user)
        notifications_count = TransactionHistory.objects.filter(
            Q(mode=TransactionHistory.request) & Q(receiver=request.user) & Q(
                status=TransactionHistory.pending)).count()

        if request.method == "POST":
            validate_recipient = __get_bool(request.POST['validate_recipient'])
            if validate_recipient:
                __make_transaction(request, TransactionHistory.request, validate_recipient)
            else:
                validate_recipient, username = __verify_user(request, TransactionHistory.request, validate_recipient)
                return render(request, 'payapp/request.html',
                              {'user': user_data, 'count': notifications_count, 'recipient_user': username,
                               'validate_recipient': validate_recipient})

        validate_recipient = False
        return render(request, 'payapp/request.html',
                      {'user': user_data, 'count': notifications_count, 'validate_recipient': validate_recipient})
    return render(request, 'register/SignIn.html')


def view_transactions(request):
    if request.user.is_authenticated:
        user_data = UserExtension.objects.get(user=request.user)
        notifications_count = TransactionHistory.objects.filter(
            Q(mode=TransactionHistory.request) & Q(receiver=request.user) & Q(
                status=TransactionHistory.pending)).count()

        if request.user.is_superuser:
            transactions_logs = TransactionHistory.objects.all()
        else:
            transactions_logs = TransactionHistory.objects.filter(
                Q(mode=TransactionHistory.transfer) & (Q(sender=request.user) | Q(receiver=request.user)))

        return render(request, 'payapp/history.html',
                      {'user': user_data, 'count': notifications_count, 'transactions_logs': transactions_logs})

    return render(request, 'register/SignIn.html')


def view_users(request):
    if request.user.is_superuser:
        user_data = UserExtension.objects.get(user=request.user)
        notifications_count = TransactionHistory.objects.filter(
            Q(mode=TransactionHistory.request) & Q(receiver=request.user) & Q(
                status=TransactionHistory.pending)).count()

        reg_users = UserExtension.objects.all()
        return render(request, 'payapp/users.html',
                      {'user': user_data, 'count': notifications_count, 'reg_users': reg_users})

    return render(request, 'register/SignIn.html')


def notification(request):
    if request.user.is_authenticated:
        user_data = UserExtension.objects.get(user=request.user)
        notifications_count = TransactionHistory.objects.filter(
            Q(mode=TransactionHistory.request) & Q(receiver=request.user) & Q(
                status=TransactionHistory.pending)).count()

        transactions_logs = TransactionHistory.objects.filter(
            Q(mode=TransactionHistory.request) & Q(receiver=request.user) & Q(status=TransactionHistory.pending))

        return render(request, 'payapp/notification_list.html',
                      {'user': user_data, 'count': notifications_count, 'transactions_logs': transactions_logs})

    return render(request, 'register/SignIn.html')


def request_decision(request, id):
    if request.user.is_authenticated:
        user_data = UserExtension.objects.get(user=request.user)
        notifications_count = TransactionHistory.objects.filter(
            Q(mode=TransactionHistory.request) & Q(receiver=request.user) & Q(
                status=TransactionHistory.pending)).count()

        transaction = TransactionHistory.objects.get(id=id)
        return render(request, 'payapp/request_decision.html',
                      {'user': user_data, 'count': notifications_count, 'transaction': transaction})

    return render(request, 'register/SignIn.html')


def request_action(request, id, decision):
    if request.user.is_authenticated:

        transaction = TransactionHistory.objects.get(id=id)

        if decision == 'accept':
            request_from = transaction.sender
            request_to = transaction.receiver
            amount = transaction.amount
            currency = transaction.currency

            request_amount = amount
            request_user = UserExtension.objects.get(user=request_from)
            donor_user = UserExtension.objects.get(user=request_to)

            if donor_user.currency != currency:
                rate, amount = get_exchange_rate(currency, donor_user.currency, amount)

            if donor_user.balance >= amount:
                TransactionHistory.objects.create(sender=donor_user.user, receiver=request_user.user, amount=request_amount, mode=TransactionHistory.transfer,
                                                  currency=request_user.currency, status=TransactionHistory.completed)

                request_user.balance += request_amount
                request_user.save()

                donor_user.balance -= amount
                donor_user.save()

                transaction.status = TransactionHistory.completed
                transaction.save()


59 PayAPP Django/PayApp/code/webapps2023/templates/payapp/history.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <style>
        /* width */
        ::-webkit-scrollbar {
            width: 10px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
            box-shadow: inset 0 0 5px grey;
            border-radius: 10px;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
            background: #57b846;
            border-radius: 10px;
        }

        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
            background: #b30000;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="contact1">
        <div class="container-contact1">
            <h1 class="" style="font-family: Montserrat-Bold; margin: 0 auto 25px auto; text-align: center">Transaction
                History</h1>

            <div class="table-wrapper" style="width: 100%; overflow-y: scroll; height: 450px">
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Date</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Transaction</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if request.user.is_superuser %}
                        {% for transaction in transactions_logs %}
                            <tr>
                                <th>{{ transaction.id }}</th>
                                <th>{{ transaction.dated_at }}</th>
                                <td>{{ transaction.amount }}</td>
                                <td>An amount of {{ transaction.amount }} {{ transaction.currency }} has been sent
                                    from {{ transaction.sender }} to {{ transaction.receiver }}</td>

                            </tr>
                        {% endfor %}
                    {% elif request.user.is_authenticated %}
                        {% for transaction in transactions_logs %}
                            <tr>
                                <th>{{ transaction.id }}</th>
                                <th>{{ transaction.dated_at }}</th>
                                <td>{{ transaction.amount }}</td>
                                {% if transaction.sender == request.user %}
                                    <td>An amount of {{ transaction.amount }} {{ transaction.currency }} sent to {{ transaction.receiver }}</td>
                                {% else %}
                                    <td>An amount of {{ transaction.amount }} {{ transaction.currency }} received from {{ transaction.sender }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>

    <footer class="bg-dark text-center text-lg-start" style="color: #ffffff">
        <div class="text-center p-3">
            &copy; 2023 Pay APP. All rights reserved.
        </div>
    </footer>

{% endblock %}

59 PayAPP Django/PayApp/code/webapps2023/templates/payapp/notification_list.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <style>
        /* width */
        ::-webkit-scrollbar {
            width: 10px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
            box-shadow: inset 0 0 5px grey;
            border-radius: 10px;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
            background: #57b846;
            border-radius: 10px;
        }

        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
            background: #b30000;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="contact1">
        <div class="container-contact1">
            <h1 class="" style="font-family: Montserrat-Bold; margin: 0 auto 25px auto; text-align: center">Transaction
                History</h1>

            <div class="table-wrapper" style="width: 100%; overflow-y: scroll; height: 450px">
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Detail</th>
                        <th scope="col">Accept/Reject</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if request.user.is_authenticated %}
                        {% for transaction in transactions_logs %}
                            <tr>
                                <th>{{ transaction.dated_at }}</th>
                                <td>An amount of {{ transaction.amount }} {{ transaction.currency }} has been requested
                                    by you on {{ transaction.dated_at }} from {{ transaction.sender }}</td>
                                <td><a href="{% url 'payapp:request_decision_id' id=transaction.id %}">click here..</a></td>

                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>

    <footer class="bg-dark text-center text-lg-start" style="color: #ffffff">
        <div class="text-center p-3">
            &copy; 2023 Pay APP. All rights reserved.
        </div>
    </footer>

{% endblock %}


{% block script %}

    <script>
        {% if messages %}
            {% for message in messages %}
                toastr.{{ message.tags }}('{{ message }}', '', {
                    positionClass: 'toast-bottom-right'
                });
            {% endfor %}
        {% endif %}
    </script>

{% endblock %}

59 PayAPP Django/PayApp/code/webapps2023/templates/payapp/request.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="contact1">
        <div class="container-contact1">

            <div class="contact1-pic js-tilt1">
                <img src="{% static 'images/coin.png' %}" alt="IMG" class="person" id="person"
                     style="width: 300px; height: 250px; max-height: 250px; max-width: 300px">
            </div>


            <form class="contact1-form validate-form" style="" method="post", action="{% url 'payapp:request' %}">
                {% csrf_token %}
                <span class="contact1-form-title">Request payment</span>

                <div class="wrap-input1 validate-input" data-validate="Message is required">
                    <input class="input1" type="hidden" name="validate_recipient" value="{{ validate_recipient }}">
                    <span class="shadow-input1"></span>
                </div>


                {% if validate_recipient %}
                    <div class="wrap-input1 validate-input" data-validate="Message is required">
                        <input class="input1" type="text" name="username" placeholder="username"
                               value="{{ recipient_user }}" readonly>
                        <span class="shadow-input1"></span>
                    </div>

                    <div class="wrap-input1 validate-input" data-validate="Message is required">
                        <input class="input1" type="number" step="0.01" name="amount" placeholder="amount">
                        <span class="shadow-input1"></span>
                    </div>
                    <div class="container-contact1-form-btn">
                        <button class="contact1-form-btn">
                    <span>
                        Request Now
                        <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    </span>
                        </button>
                    </div>
                {% else %}
                    <div class="wrap-input1 validate-input" data-validate="Message is required">
                        <input class="input1" type="text" name="username" placeholder="username">
                        <span class="shadow-input1"></span>
                    </div>
                    <div class="container-contact1-form-btn">
                        <button class="contact1-form-btn">
                    <span>
                        Verify Now
                        <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    </span>
                        </button>
                    </div>
                {% endif %}




            </form>
        </div>
    </div>

    <footer class="bg-dark text-center text-lg-start" style="color: #ffffff">
        <div class="text-center p-3">
            &copy; 2023 Pay APP. All rights reserved.
        </div>
    </footer>

{% endblock %}


{% block script %}

    <script>
        {% if messages %}
            {% for message in messages %}
                toastr.{{ message.tags }}('{{ message }}', '', {
                    positionClass: 'toast-bottom-right'
                });
            {% endfor %}
        {% endif %}
    </script>

{% endblock %}

59 PayAPP Django/PayApp/code/webapps2023/templates/payapp/request_decision.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="contact1">
        <div class="container-contact1">

            <div class="contact1-pic js-tilt1">
                <img src="{% static 'images/coin.png' %}" alt="IMG" class="person" id="person"
                     style="width: 300px; height: 250px; max-height: 250px; max-width: 300px">
            </div>


            <form class="contact1-form validate-form" style="">
                {% csrf_token %}
                <span class="contact1-form-title">Take Decision on Request</span>


                <div class="wrap-input1 validate-input" data-validate="Message is required">
                    <input class="input1" type="text" name="username" placeholder="username"
                           value="{{ transaction.sender }}" readonly>
                    <span class="shadow-input1"></span>
                </div>

                <div class="wrap-input1 validate-input" data-validate="Message is required">
                    <input class="input1" type="text" step="0.01" name="amount_display" placeholder="amount"
                           value="{{ transaction.amount }} {{ transaction.currency }}">
                    <span class="shadow-input1"></span>
                </div>


                <div class="container-contact1-form-btn">
                    <a class="contact1-form-btn" href="{% url 'payapp:request_action' id=transaction.id decision='accept' %}">
                    <span>
                        Accept
                        <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    </span>
                    </a>

                    <a class="contact1-form-btn" href="{% url 'payapp:request_action' id=transaction.id decision='reject' %}">
                    <span>
                        Reject
                        <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    </span>
                    </a>
                </div>




            </form>
        </div>
    </div>

    <footer class="bg-dark text-center text-lg-start" style="color: #ffffff">
        <div class="text-center p-3">
            &copy; 2023 Pay APP. All rights reserved.
        </div>
    </footer>

{% endblock %}


{% block script %}

    <script>
        {% if messages %}
            {% for message in messages %}
                toastr.{{ message.tags }}('{{ message }}', '', {
                    positionClass: 'toast-bottom-right'
                });
            {% endfor %}
        {% endif %}
    </script>

{% endblock %}

59 PayAPP Django/PayApp/code/webapps2023/templates/payapp/transfer.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="contact1">
        <div class="container-contact1">

            <div class="contact1-pic js-tilt1">
                <img src="{% static 'images/coin.png' %}" alt="IMG" class="person" id="person"
                     style="width: 300px; height: 250px; max-height: 250px; max-width: 300px">
            </div>


            <form class="contact1-form validate-form" style="" method="post" , action="{% url 'payapp:transfer' %}">
                {% csrf_token %}
                <span class="contact1-form-title">Payment Transfer</span>

                <div class="wrap-input1 validate-input" data-validate="Message is required">
                    <input class="input1" type="hidden" name="validate_recipient" value="{{ validate_recipient }}">
                    <span class="shadow-input1"></span>
                </div>

                {% if validate_recipient %}
                    <div class="wrap-input1 validate-input" data-validate="Message is required">
                        <input class="input1" type="text" name="username" placeholder="username"
                               value="{{ recipient_user }}" readonly>
                        <span class="shadow-input1"></span>
                    </div>

                    <div class="wrap-input1 validate-input" data-validate="Message is required">
                        <input class="input1" type="number" step="0.01" name="amount" placeholder="amount">
                        <span class="shadow-input1"></span>
                    </div>
                    <div class="container-contact1-form-btn">
                        <button class="contact1-form-btn">
                    <span>
                        Transfer Now
                        <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    </span>
                        </button>
                    </div>
                {% else %}
                    <div class="wrap-input1 validate-input" data-validate="Message is required">
                        <input class="input1" type="text" name="username" placeholder="username">
                        <span class="shadow-input1"></span>
                    </div>
                    <div class="container-contact1-form-btn">
                        <button class="contact1-form-btn">
                    <span>
                        Verify Now
                        <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    </span>
                        </button>
                    </div>
                {% endif %}




            </form>
        </div>
    </div>

    <footer class="bg-dark text-center text-lg-start" style="color: #ffffff">
        <div class="text-center p-3">
            &copy; 2023 Pay APP. All rights reserved.
        </div>
    </footer>

{% endblock %}


{% block script %}

    <script>
        {% if messages %}
            {% for message in messages %}
                toastr.{{ message.tags }}('{{ message }}', '', {
                    positionClass: 'toast-bottom-right'
                });
            {% endfor %}
        {% endif %}
    </script>

{% endblock %}

59 PayAPP Django/PayApp/code/webapps2023/templates/payapp/users.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <style>
        /* width */
        ::-webkit-scrollbar {
            width: 10px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
            box-shadow: inset 0 0 5px grey;
            border-radius: 10px;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
            background: #57b846;
            border-radius: 10px;
        }

        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
            background: #b30000;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="contact1">
        <div class="container-contact1">
            <h1 class="" style="font-family: Montserrat-Bold; margin: 0 auto 25px auto; text-align: center">Transaction
                History</h1>

            <div class="table-wrapper" style="width: 100%; overflow-y: scroll; height: 450px">
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Username</th>
                        <th scope="col">Balance</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if request.user.is_superuser %}
                        {% for reg_user in reg_users %}
                            <tr>
                                <th>{{ reg_user.f_name }}</th>
                                <th>{{ reg_user.l_name }}</th>
                                <td>{{ reg_user.user.username }}</td>
                                <td>{{ reg_user.balance }} {{ reg_user.currency }}</td>

                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>

    <footer class="bg-dark text-center text-lg-start" style="color: #ffffff">
        <div class="text-center p-3">
            &copy; 2023 Pay APP. All rights reserved.
        </div>
    </footer>

{% endblock %}